spring:
  application:
    name: user-management
  datasource:
    url: jdbc:postgresql://metro.proxy.rlwy.net:48912/railway
    username: postgres
    password: bWmvSAaqdshusfQVjbTdrBVlaidqqnYg
    driver-class-name: org.postgresql.Driver 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true