spring:
  application:
    name: user-management
  datasource:
    url: mysql://root:QpYLoAKVdOWwIsJviFFTRZXgwyCGjoiO@yamanote.proxy.rlwy.net:53532/railway
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
