spring:
  datasource:
    url: jdbc:postgresql://ballast.proxy.rlwy.net:16574/railway
    username: postgres
    password: BlcyLZeoERNeRMJxfMSjxfGoBraAtrfv
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true