spring:
  application:
    name: user-management
  datasource:
    url: jdbc:postgresql://localhost:5432/myappdb
    username: myappuser
    password: myapppassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true