spring:
  application:
    name: user-management
  datasource:
    url: jdbc:postgresql://postgres:lcUgePoRjXCycaDdgjcVEQONIHxsqUUJ@caboose.proxy.rlwy.net:44635/railway
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
